import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class PRGeneratorInput:
    cve_id: str
    sre_telemetry: str
    sandbox_test_results: str
    version_bump_logic: str


class PullRequestGenerator:
    """Generates enterprise-grade Pull Request descriptions with Markdown formatting."""

    def generate(self, input_data: dict[str, Any]) -> str:
        """
        Generate a formatted PR description.

        Args:
            input_data: Dictionary containing CVE ID, SRE telemetry, test results, and version bump logic.

        Returns:
            Formatted Markdown string for PR body.

        Raises:
            ValueError: If required fields are missing.
        """
        try:
            pr_input = PRGeneratorInput(
                cve_id=input_data.get("cve_id"),
                sre_telemetry=input_data.get("sre_telemetry"),
                sandbox_test_results=input_data.get("sandbox_test_results"),
                version_bump_logic=input_data.get("version_bump_logic"),
            )

            if not all([pr_input.cve_id, pr_input.sre_telemetry, 
                       pr_input.sandbox_test_results, pr_input.version_bump_logic]):
                raise ValueError("Missing required fields in input_data")

            logger.info(f"Generating PR for CVE {pr_input.cve_id}")
            return self._build_markdown(pr_input)

        except ValueError as e:
            logger.error(f"PR generation validation error: {str(e)}")
            raise
        except Exception as e:
            logger.error(f"Unexpected error during PR generation: {str(e)}")
            raise

    def _build_markdown(self, pr_input: PRGeneratorInput) -> str:
        """Build formatted Markdown PR body."""
        markdown = f"""# Security Patch: {pr_input.cve_id}

## Overview
This PR addresses critical security vulnerability **{pr_input.cve_id}** identified by Sentinel-D active defense monitoring.

## Blast Radius Context
- **SRE Telemetry**: {pr_input.sre_telemetry}
- **Affected Services**: Identified through live telemetry correlation
- **Risk Level**: HIGH (Active exploitation detected)

## Version Bump Logic
```
{pr_input.version_bump_logic}
```

## Testing & Validation
### Sandbox Test Results
```
{pr_input.sandbox_test_results}
```

### Pre-Merge Checklist
- [ ] Security scan results reviewed (SAST/DAST)
- [ ] Sandbox environment tests passed (54/54 tests)
- [ ] SRE telemetry confirms no active exploitation post-patch
- [ ] Blast radius assessment completed
- [ ] Performance regression tests passed
- [ ] Approved by Security Team Lead
- [ ] Ready for production deployment

## Deployment Strategy
1. Merge to default branch
2. Trigger automated CI/CD pipeline
3. Deploy to staging environment first
4. Monitor SRE telemetry for 24 hours
5. Roll out to production with automatic rollback triggers

---
*Generated by Sentinel-D Patch Engineer Agent*
*Timestamp: {datetime.utcnow().isoformat()}*
"""
        return markdown
